spring:
  config:
    activate:
      on-profile: prod

  # [RDS 데이터베이스 연결]
  datasource:
    url: jdbc:postgresql://gitget-db.ch2662mu8mgf.ap-northeast-2.rds.amazonaws.com:5432/gitget
    username: postgres
    password: globoo1234
    driver-class-name: org.postgresql.Driver

  # [JPA 설정 - 운영 환경용]
  jpa:
    hibernate:
      ddl-auto: update  # 처음엔 update로 테이블 생성, 나중엔 validate나 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false # 운영에선 쿼리 로그 끄는게 성능에 좋음

  # [메일 설정 - 실제 비밀번호 입력]
  mail:
    host: smtp.gmail.com # (예시: 구글이라면)
    port: 587
    username: danieljjs77@gmail.com
    password: "*pearl004" # 구글 앱 비밀번호 등 실제 값
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: no-reply@globoo.com

# [JWT 비밀키 - 실제 값 입력]
jwt:
  issuer: Globoo
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 1209600
  secret: 3c7f9d2a1b8e4f5a6c9d0b2e5f8a1c4b7d0e3f6a9c2b5d8e1f4a7c0b3d6e9f2a5c8b1d4e7f0a3c6b9d2e5f8a1c4b7d0e3f6a9c2b5d8e1f4a7c0b3d6e9f2a
  # 예: VlwEyVlpkZ9WsRC1r8yrzsfjj4230d0f... (Base64 인코딩된 긴 문자열 권장)

server:
  port: 8080
  forward-headers-strategy: framework